Revert "Advertise TS_SSL feature with OpenSSL >= 1.1.0."
This reverts commit 281c84fc3996c757efdf6e9b3f906d7a1fc08b1d.

Indeed openssl can be built on toolchains without threads support which
will result in the following build failure:

ne_openssl.c:43:10: fatal error: pthread.h: No such file or directory
   43 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/da995ef26001357e51a5907de9c6111b9ff89bdf

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>